apiVersion: v1
kind: PersistentVolume
metadata:
  name: mlflow-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/mlflow-data  # EC2 host path where MLflow DB and artifacts are persisted
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  claimRef:
    namespace: airflow-my-namespace
    name: mlflow-pvc
