apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-outputtextwriter
  namespace: airflow-my-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: /home/ubuntu/airflow/dag-mylogs  # updated path to match deploy.sh sync destination
  persistentVolumeReclaimPolicy: Retain  # If this pv is deleted, the log files keep existing
  storageClassName: manual  # Add to a manually named storage class which I am calling here "manual"