apiVersion: v1
kind: Service
metadata:
  name: flask-service-expose-port
  namespace: default
spec:
  selector:
    # app: my-kuber-pod-flask  # Before I was using labels # Must match the pod’s label in kubernetesPod_flask.yaml, in metadata section, in "name:" section
    app: dancing-flask-pod
  ports:
  - protocol: TCP
    port: 80       # Port exposed in the internal cluster
    targetPort: 5000  # Pod’s Flask port
    nodePort: 32147  # External port to expose publicly (# Note: Default potential exposed Kubernetes ports: Between 30000 and 32767)
  type: NodePort   # Exposes on a high port (30000-32767) on the node’s IP